######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 8 10:37:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += borrowersearch.h mainwindow.h
FORMS += borrowersearch.ui mainwindow.ui
SOURCES += borrowersearch.cpp main.cpp mainwindow.cpp
RESOURCES += koc.qrc
QT += sql

CONFIG += debug
