######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 7 12:15:22 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += koc.qrc
